/* Generated by scripts/photo-dims.py: the pixel size of every photo, so a sheet can take
   the photo's own proportion and the browser can reserve the space before it loads. */
export const photoDims: Record<string, readonly [number, number]> = {
  "/assets/improved-v2/hero/building-signs.jpg": [865, 540],
  "/assets/improved-v2/hero/construction-signage.jpg": [1025, 1445],
  "/assets/improved-v2/hero/lobby-signs.jpg": [1920, 1440],
  "/assets/improved-v2/hero/vehicle-wraps.jpg": [1600, 1100],
  "/assets/improved-v2/services/banners.jpg": [460, 316],
  "/assets/improved-v2/services/building-signs.jpg": [1600, 1200],
  "/assets/improved-v2/services/custom-signs.jpg": [980, 660],
  "/assets/improved-v2/services/embroidery.jpg": [799, 584],
  "/assets/improved-v2/services/laser-engraving.jpg": [1530, 370],
  "/assets/improved-v2/services/lobby-signs.jpg": [1140, 615],
  "/assets/improved-v2/services/special-projects.jpg": [1920, 1190],
  "/assets/improved-v2/services/wall-graphics.jpg": [1755, 1015],
  "/assets/improved-v2/services/wraps.jpg": [1189, 740],
};
export const photoAspect = (src: string | null | undefined) => { const d = src ? photoDims[src] : undefined; return d ? `${d[0]} / ${d[1]}` : undefined; };
