# Rewrites src/content/photoDims.ts from the photos under public/assets/improved-v2 and public/assets/live.
import subprocess, glob
out=['/* Generated by scripts/photo-dims.py: the pixel size of every photo, so a sheet can take',
     '   the photo\'s own proportion and the browser can reserve the space before it loads. */',
     'export const photoDims: Record<string, readonly [number, number]> = {']
files=sorted(glob.glob('src/assets/photos/**/*.jpg', recursive=True))
for f in files:
    w,h=subprocess.run(['magick','identify','-format','%w %h',f],capture_output=True,text=True).stdout.split()
    out.append(f'  "{f.replace('src/assets/photos','/assets')}": [{w}, {h}],')
out.append('};')
out.append('export const photoAspect = (src: string | null | undefined) => { const d = src ? photoDims[src] : undefined; return d ? `${d[0]} / ${d[1]}` : undefined; };')
open('src/content/photoDims.ts','w').write('\n'.join(out)+'\n')
